tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "on-primary-container": "#f7fff2",
        "on-primary-fixed-variant": "#005320",
        "primary-container": "#00873a",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#bec6e0",
        tertiary: "#4d5d73",
        "secondary-fixed": "#dae2fd",
        "tertiary-fixed": "#d3e4fe",
        "inverse-surface": "#2d3133",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary-fixed": "#002109",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        surface: "#f7f9fb",
        "outline-variant": "#bdcaba",
        "surface-tint": "#006e2d",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#66768d",
        "primary-fixed-dim": "#62df7d",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#b7c8e1",
        "inverse-primary": "#62df7d",
        "on-tertiary-container": "#fdfcff",
        primary: "#006b2c",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed-variant": "#3f465c",
        background: "#f7f9fb",
        "on-secondary-container": "#5c647a",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#7ffc97",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-dim": "#d8dadc",
        outline: "#6e7b6c",
        secondary: "#565e74",
        "error-container": "#ffdad6",
        "secondary-container": "#dae2fd",
        "on-background": "#191c1e",
        "on-surface-variant": "#3e4a3d",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
};
